In [37]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  

In [39]:
#importing datasets  
data_set= pd.read_csv('D:\Ardhi\Ecoinvent\cut-off-system-model\sample_eco_lcia.csv')  
  
#Extracting Independent and dependent Variable  
x= data_set.iloc[:,[6,7,8,9,10,11,12,13,14,15,16]].values  
y= data_set.iloc[:,[1]].values  
  
#print(x)
#print(y)

from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  


#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  


from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5)  
classifier.fit(x_train, y_train.ravel())  


y_pred= classifier.predict(x_test) 

print(y_pred)

['4-methyl-2-pentanone production'
 'C3 hydrocarbon production, mixture, petroleum refinery operation'
 'NMC111 oxide production, for Li-ion battery'
 'N,N-dimethylformamide production' 'Mannheim process'
 'NMC111 oxide production, for Li-ion battery'
 '3-methyl-1-butyl acetate production'
 'NMC111 hydroxide production, for Li-ion battery'
 'acrylic binder production, with water, in 54% solution state'
 'Sohio process' '4-tert-butyltoluene production' 'Sohio process'
 '2,4-dichlorophenol production' 'Mannheim process'
 '4-tert-butyltoluene production' 'NPK (15-15-15) fertiliser production'
 'EUR-flat pallet production' 'Sohio process'
 'acrylic varnish production, with water, in 53% solution state'
 '3-methyl-1-butyl acetate production'
 'C3 hydrocarbon production, mixture, petroleum refinery operation'
 '1,1-difluoroethane production, HFC-152a' '2-pyridinol production'
 '4-methyl-2-pentanone production' 'acetanilide production'
 '2-methyl-2-butanol production' 'aclonifen production'
 

In [41]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [42]:
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
